import express from "express";
import cors from "cors";
import helmet from "helmet";
import { rateLimit } from "express-rate-limit";
import pinoHttp from "pino-http";
import cookieParser from "cookie-parser";
import { apiRouter } from "./routes/index.js";
import { authRouter } from "./routes/auth.js";
import { accountRouter } from "./routes/account.js";
import { draftRouter } from "./routes/drafts.js";
import { errorHandler, notFound } from "./lib/errors.js";
import { authenticate, validateCsrf, validateOrigin } from "./middleware/auth.js";

export const app = express();
app.set("trust proxy", 1);
app.use(pinoHttp());
app.use(helmet({contentSecurityPolicy:false}));
app.use(cors({origin:(process.env.WEB_ORIGIN ?? "http://localhost:3000").split(","),credentials:true}));
app.use(express.json({limit:"512kb"}));
app.use(cookieParser());
app.use(rateLimit({windowMs:60_000,limit:300,standardHeaders:"draft-8",legacyHeaders:false}));
app.use(validateOrigin);
app.get("/api/v1/health", (_request, response) => response.json({ status: "ok", service: "codemuscle-api" }));
app.use("/api/v1/auth", authRouter);
app.use("/api/v1", authenticate, validateCsrf);
app.use("/api/v1", accountRouter);
app.use("/api/v1", draftRouter);
app.use("/api/v1",apiRouter);
app.use(notFound);
app.use(errorHandler);
